language: c

os:
    - linux
    - osx

sudo: false

env:
    # CONDA_JWST_DEPENDENCIES is used because CONDA_DEPENDENCIES is not truly global.
    global:
        - MAIN_CMD='python setup.py'
        - CONDA_CHANNELS='http://ssb.stsci.edu/astroconda'
        - CONDA_DEPENDENCIES='fitsverify'
        - PIP_DEPENDENCIES='numpy coveralls'
        - CRDS_SERVER_URL='https://hst-crds.stsci.edu'
        - CRDS_TEST_ROOT=/tmp

    matrix:
        - PYTHON_VERSION=3.7
        - PYTHON_VERSION=3.8

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
    - pip install git+https://github.com/spacetelescope/jwst
    - pip uninstall --yes crds
    - ./install
    - pip install .["submission","test","docs"]
    - pip freeze
    - ./setup_test_cache $CRDS_TEST_ROOT

script:
    - conda info
    - pip freeze
    - ./runtests --cover

# after_success:
#     coveralls
